### ISSUE TITLE
Failure to delete folder and crash

### ISSUE THREAD

**Issue by codersx** [pwnlogs/cert-fixer#1]
I don't know if this has anything to do with it. When I reboot when I have Charles and a special certificate (2 certificates) the phone crashes. It won't turn on again.

Device: SM-A155F / Android 14
Log:
```
+ umount /data/local/tmp/adg-ca-copy
+ rmdir /data/local/tmp/adg-ca-copy
rmdir: '/data/local/tmp/adg-ca-copy': Device or resource busy
+ read USER_CERT_HASH
+ echo '[i] Cert-Fixer execution completed'
```

**Comment by pwnlogs** [comment]
@codersx ,Did you manage to solve the issue?  
As per your logs, only `rmdir` failed. As you might have gussed, its only a temporary directory and it should not crash your device. Make sure your certificates are in the right format. Cert-fixer picks your certificates from the user store. If you managed to install the certificate in user store, then the certificate are in the right format.
